
#ifndef NFLAMBDA_RUNTIME_PARSE_CONFIG_H
#define NFLAMBDA_RUNTIME_PARSE_CONFIG_H


enum parseState{
    PARSE_STATE_OPTION,
    PARSE_STATE_VALUE,
    PARSE_STATE_END
};

#endif //NFLAMBDA_RUNTIME_PARSE_CONFIG_H
